/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_binbzha_xiaogua_Kws */

#ifndef _Included_com_example_binbzha_xiaogua_Kws
#define _Included_com_example_binbzha_xiaogua_Kws
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_binbzha_xiaogua_Kws
 * Method:    Hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_binbzha_xiaogua_Kws_Hello
  (JNIEnv *, jobject);

/*
 * Class:     com_example_binbzha_xiaogua_Kws
 * Method:    Init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_binbzha_xiaogua_Kws_Init
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_example_binbzha_xiaogua_Kws
 * Method:    DetectOnline
 * Signature: ([SZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_binbzha_xiaogua_Kws_DetectOnline
  (JNIEnv *, jobject, jshortArray, jboolean);

/*
 * Class:     com_example_binbzha_xiaogua_Kws
 * Method:    Reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_binbzha_xiaogua_Kws_Reset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
